[package]
name = "cucumber_rust"
version = "0.7.0"
authors = ["Brendan Molloy <brendan@bbqsrc.net>"]
description = "Cucumber testing framework for Rust. Fully native, no external test runners or dependencies."
license = "MIT OR Apache-2.0"
readme = "README.md"
keywords = ["cucumber", "testing", "bdd", "atdd"]
repository = "https://github.com/bbqsrc/cucumber-rust"
documentation = "https://docs.rs/cucumber_rust"
homepage = "https://github.com/bbqsrc/cucumber-rust"
edition = "2018"

[dependencies]
gherkin = { package = "gherkin_rust", git = "https://github.com/bbqsrc/gherkin-rust" }

async-stream = "0.2.1"
async-trait = "0.1.31"
cute_custom_default = "2.1.0"
futures = "0.3.5"
globwalk = "0.8.0"
regex = "1.3.7"
shh = "1.0.1"
thiserror = "1.0.18"
termcolor = "1.1.0"
textwrap = { version = "0.11", features = ["term_size"] }
pathdiff = "0.2.0"
junit-report = { git = "https://github.com/Puciek/junit-report-rs", branch = "features/support-for-std-#8" }

[[test]]
name = "cucumber_builder"
harness = false
